Repository Co-Laon/claon-app, pull requests merged in 2022-12, with the labels that each got.

#156 docs: 커밋 컨벤션 추가
  CONTRIBUTING.md
Labels: documentation

#157 refactor: Alert 관련 컴포넌트 리팩터링
  packages/climbingweb/pages/_app.tsx
  packages/climbingweb/pages/center/request/[cid].tsx
  packages/climbingweb/pages/report/[fid].tsx
  packages/climbingweb/pages/users/me/laon/index.tsx
  packages/climbingweb/src/components/CreateFeed/SelectHoldList/HoldListModal.tsx
  packages/climbingweb/src/components/common/Alert/Alert.tsx
  packages/climbingweb/src/components/common/Toast/Toast.tsx
  packages/climbingweb/src/components/common/Toast/ToastClient.tsx
  packages/climbingweb/src/hooks/useToast.ts
Labels: refactor

#158 fix: UserHead 컴포넌트 apeIndex 표기 오류 수정
  packages/climbingweb/src/components/User/UserHead.tsx
Labels: bug

#161 feat: 포스트 이미지 업로드 구현
  packages/climbingweb/pages/feed/create/index.tsx
  packages/climbingweb/src/components/CreateFeed/UploadImageList/UploadImage.tsx
  packages/climbingweb/src/components/CreateFeed/UploadImageList/UploadImageButton.tsx
  packages/climbingweb/src/components/CreateFeed/UploadImageList/index.tsx
  packages/climbingweb/src/hooks/queries/post/queries.ts
  packages/climbingweb/src/hooks/queries/post/queryKey.ts
  packages/climbingweb/src/hooks/useCreatePostForm.ts
  packages/climbingweb/src/store/slices/createFeed.ts
  packages/climbingweb/src/store/slices/index.ts
Labels: enhancement

#167 Fix/app
  packages/climbingapp/.gitignore
  packages/climbingapp/android/app/build.gradle
  packages/climbingapp/android/app/src/main/AndroidManifest.xml
  packages/climbingapp/android/build.gradle
  packages/climbingapp/android/gradle.properties
  packages/climbingapp/package.json
  packages/climbingapp/src/component/button/Button.tsx
  packages/climbingapp/src/component/button/buttonProps.tsx
  packages/climbingapp/src/component/profile-image/ProfileImage.tsx
  packages/climbingapp/src/component/text/AuthTitle.tsx
  packages/climbingapp/src/component/view/ScreenView.tsx
  packages/climbingapp/src/component/webview/CustomWebView.tsx
  packages/climbingapp/src/hooks/useAuth.ts
  packages/climbingapp/src/hooks/useImagePicker.ts
  packages/climbingapp/src/navigation/LoginNavigator.tsx
  packages/climbingapp/src/navigation/index.tsx
  packages/climbingapp/src/navigation/screens/auth/ConnectWithInstagramScreen.tsx
  packages/climbingapp/src/navigation/screens/auth/LoginScreen.tsx
  packages/climbingapp/src/navigation/screens/auth/RegisterScreen.tsx
  packages/climbingapp/src/navigation/screens/auth/SignUpStepOneScreen.tsx
  packages/climbingapp/src/navigation/screens/auth/SignUpStepTwoScreen.tsx
  packages/climbingapp/src/navigation/screens/auth/type.d.ts
  packages/climbingapp/src/store/slices/authInfo.ts
  packages/climbingapp/src/utils/constants.ts
  yarn.lock
Labels: enhancement, fix, chore

#173 스켈레톤 구현 피드, 댓글, 암장사진, 검색 시 암장, 유저리스트, 마이페이지 기록, 피드
  packages/climbingweb/src/components/Comments/Comments.tsx
  packages/climbingweb/src/components/HomeFeed/HomeFeed.tsx
  packages/climbingweb/src/components/SearchResult/UserResult/UserResult.tsx
  packages/climbingweb/src/components/User/UserFeed.tsx
  packages/climbingweb/src/components/User/UserRecord.tsx
  packages/climbingweb/src/components/common/CenterResult/CenterResult.tsx
  packages/climbingweb/src/components/common/ImageList/index.tsx
  packages/climbingweb/src/components/common/skeleton/CenterImageSkeleton.tsx
  packages/climbingweb/src/components/common/skeleton/CenterResultSkeleton.tsx
  packages/climbingweb/src/components/common/skeleton/CommentSkeleton.tsx
  packages/climbingweb/src/components/common/skeleton/FeedSkeleton.tsx
  packages/climbingweb/src/components/common/skeleton/Skeleton.stories.tsx
  packages/climbingweb/src/components/common/skeleton/UserFeedSkeleton.tsx
  packages/climbingweb/src/components/common/skeleton/UserRecordSkeleton.tsx
  packages/climbingweb/src/components/common/skeleton/UserResultSkeleton.tsx
Labels: enhancement

#178 chore: firebase에 도메인 호스팅 및 CD 설정
  .github/workflows/firebase-hosting-merge.yml
  .github/workflows/firebase-hosting-pull-request.yml
  packages/climbingweb/.firebaserc
  packages/climbingweb/.gitignore
  packages/climbingweb/firebase.json
Labels: chore
