Repository Co-Laon/claon-app, pull requests merged in 2022-07, with the labels that each got.

#59 feat: implement KakaoLogin
  packages/climbingapp/android/app/src/main/AndroidManifest.xml
  packages/climbingapp/android/app/src/main/res/values/strings.xml
  packages/climbingapp/android/build.gradle
  packages/climbingapp/ios/Podfile.lock
  packages/climbingapp/ios/climbingApp-Bridging-Header.h
  packages/climbingapp/ios/climbingApp.xcodeproj/project.pbxproj
  packages/climbingapp/ios/climbingApp/AppDelegate.m
  packages/climbingapp/ios/climbingApp/Info.plist
  packages/climbingapp/package.json
  packages/climbingapp/src/component/checkbox/Checkbox.stories.tsx
  packages/climbingapp/src/component/dropdown/DropDown.stories.tsx
  packages/climbingapp/src/hooks/useAuth.ts
  packages/climbingapp/src/navigation/index.tsx
  packages/climbingapp/src/navigation/screens/auth/LoginScreen.tsx
  packages/climbingapp/src/navigation/screens/auth/WelcomeScreen.tsx
  packages/climbingapp/src/store/slices/auth.ts
  tailwind.config.js
  yarn.lock
Labels: enhancement

#68 feat: implement Google Login
  packages/climbingapp/ios/Podfile.lock
  packages/climbingapp/ios/climbingApp/AppDelegate.m
  packages/climbingapp/ios/climbingApp/Info.plist
  packages/climbingapp/package.json
  packages/climbingapp/src/hooks/useAuth.ts
  packages/climbingapp/src/navigation/screens/auth/LoginScreen.tsx
  packages/climbingapp/src/navigation/screens/auth/WelcomeScreen.tsx
  packages/climbingapp/src/store/slices/auth.ts
  yarn.lock
Labels: enhancement, chore

#69 chore: fix config for hide app key
  packages/climbingapp/.gitignore
  packages/climbingapp/android/app/build.gradle
  packages/climbingapp/android/app/src/main/AndroidManifest.xml
  packages/climbingapp/ios/Config.xcconfig
  packages/climbingapp/ios/Podfile.lock
  packages/climbingapp/ios/climbingApp.xcodeproj/project.pbxproj
  packages/climbingapp/ios/climbingApp.xcodeproj/xcshareddata/xcschemes/climbingApp.xcscheme
  packages/climbingapp/ios/climbingApp/Info.plist
  packages/climbingapp/package.json
  packages/climbingapp/src/hooks/useAuth.ts
  yarn.lock
Labels: chore

#70 refactor: refactor pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: refactor

#71 fix: fix android configuration for .env
  packages/climbingapp/android/app/build.gradle
  packages/climbingapp/ios/climbingApp.xcodeproj/project.pbxproj
  packages/climbingapp/ios/climbingApp.xcodeproj/xcshareddata/xcschemes/climbingApp.xcscheme
Labels: fix

#72 feat: implement login process function
  package-lock.json
  packages/climbingapp/android/build.gradle
  packages/climbingapp/ios/Podfile.lock
  packages/climbingapp/ios/climbingApp.xcodeproj/project.pbxproj
  packages/climbingapp/ios/climbingApp.xcodeproj/xcshareddata/xcschemes/climbingApp.xcscheme
  packages/climbingapp/ios/climbingApp/AppDelegate.m
  packages/climbingapp/ios/climbingApp/Info.plist
  packages/climbingapp/ios/climbingApp/LaunchScreen.storyboard
  packages/climbingapp/ios/climbingAppTests/Info.plist
  packages/climbingapp/package.json
  packages/climbingapp/src/component/bottomSheet/BottomSheet.tsx
  packages/climbingapp/src/component/button/Button.tsx
  packages/climbingapp/src/component/button/buttonProps.tsx
  packages/climbingapp/src/component/profile-image/InstaImage.tsx
  packages/climbingapp/src/component/profile-image/ProfileImage.tsx
  packages/climbingapp/src/component/text-input/TextInput.tsx
  packages/climbingapp/src/component/webview/InstagramAuthWebview.tsx
  packages/climbingapp/src/hooks/useAuth.ts
  packages/climbingapp/src/hooks/useImagePicker.ts
  packages/climbingapp/src/navigation/LoginNavigator.tsx
  packages/climbingapp/src/navigation/screens/auth/ConnectWithInstagramScreen.tsx
  packages/climbingapp/src/navigation/screens/auth/EssentialInfoScreen.tsx
  packages/climbingapp/src/navigation/screens/auth/LoginScreen.tsx
  packages/climbingapp/src/navigation/screens/auth/RegisterScreen.tsx
  packages/climbingapp/src/navigation/screens/auth/type.d.ts
  packages/climbingapp/src/store/slices/authInfo.ts
  packages/climbingapp/src/store/slices/index.ts
  yarn.lock
Labels: bug, enhancement
