Repository Co-Laon/claon-app, pull requests merged in 2022-10, with the labels that each got.

#130 feat: 새 게시글 입력 data form 로직 추가 (사진 부분 제외)
  packages/climbingweb/pages/_app.tsx
  packages/climbingweb/pages/feed/create/index.tsx
  packages/climbingweb/src/components/CreateFeed/CenterSearchInput.tsx
  packages/climbingweb/src/components/CreateFeed/SelectHoldList/HoldListModal.tsx
  packages/climbingweb/src/components/common/AppBar/NextButton.tsx
  packages/climbingweb/src/hooks/queries/center-controller/useCreatePost.ts
  packages/climbingweb/src/hooks/queries/center-controller/useFindHoldInfoByCenter.ts
  packages/climbingweb/src/hooks/queries/center-controller/useSearchCenterName.ts
  packages/climbingweb/src/hooks/queries/storage-controller/upload.ts
  packages/climbingweb/src/interface/CenterName.ts
  packages/climbingweb/src/interface/Hold.ts
Labels: enhancement

#132 chore: .env 환경변수 추가 및 웹 환경 작업 시 마스터 토큰 적용
  packages/climbingweb/pages/_app.tsx
Labels: chore

#136 chore: response 타입 정의
  packages/climbingweb/types/common/index.ts
  packages/climbingweb/types/request/center/index.d.ts
  packages/climbingweb/types/request/notice/index.d.ts
  packages/climbingweb/types/request/post/index.d.ts
  packages/climbingweb/types/request/user/index.d.ts
  packages/climbingweb/types/response/center/index.ts
  packages/climbingweb/types/response/laon/index.ts
  packages/climbingweb/types/response/notice/index.d.ts
  packages/climbingweb/types/response/post/index.d.ts
  packages/climbingweb/types/response/user/index.d.ts
Labels: chore

#138 feat&chore: fid 페이지 백엔드 로직 추가, hooks 디렉터리 변경에 따른 import 주소 변경
  packages/climbingweb/pages/feed/[fid].tsx
  packages/climbingweb/src/components/CenterInfo/CenterDetailInfo/CenterCharge.tsx
  packages/climbingweb/src/components/CenterInfo/CenterDetailInfo/CenterDetailInfo.tsx
  packages/climbingweb/src/components/CenterInfo/CenterDetailInfo/CenterHoldList.tsx
  packages/climbingweb/src/components/CenterInfo/CenterDetailInfo/CenterOperatingTime.tsx
  packages/climbingweb/src/components/CenterInfo/CenterDetailInfo/CenterPost.tsx
  packages/climbingweb/src/components/CenterInfo/CenterDetailInfo/CenterReview.tsx
  packages/climbingweb/src/components/CenterInfo/CenterDetailInfo/CenterSectorList.tsx
  packages/climbingweb/src/components/CenterInfo/CenterInfoContent.tsx
  packages/climbingweb/src/components/CreateFeed/CenterSearchInput.tsx
  packages/climbingweb/src/components/CreateFeed/SelectHoldList/HoldListModal.tsx
  packages/climbingweb/src/components/HomeFeed/FeedContent/FeedContent.tsx
  packages/climbingweb/src/components/HomeFeed/FeedHeader/FeedHeader.tsx
  packages/climbingweb/src/components/HomeFeed/FeedSectorInfo/FeedSectorInfo.tsx
  packages/climbingweb/src/components/HomeFeed/HomeFeed.tsx
  packages/climbingweb/src/components/ImageSlider/ImageSlider.tsx
  packages/climbingweb/src/components/SearchResult/UserResult/UserResult.tsx
  packages/climbingweb/src/hooks/queries/center/useGetCenterPosts.ts
  packages/climbingweb/src/hooks/queries/post/useCreateLike.ts
  packages/climbingweb/src/hooks/queries/post/useDeleteLike.ts
  packages/climbingweb/src/hooks/queries/post/useFindAllChildrenComment.ts
  packages/climbingweb/src/hooks/queries/post/useFindAllParentCommentAndThreeChildComment.ts
  packages/climbingweb/src/hooks/queries/post/useGetPost.ts
Labels: enhancement, chore
