Repository Co-Laon/claon-app, pull requests merged in 2022-09, with the labels that each got.

#104 feat: implement SettingPage >> EditMyInfo view
  packages/climbingweb/pages/SettingPage.tsx
  packages/climbingweb/src/components/SettingInfo/EditMyInfo.tsx
  packages/climbingweb/src/components/SettingInfo/SettingList.tsx
  packages/climbingweb/src/components/common/BottomSheetContents/areaSheet/AreaSheet.tsx
  packages/climbingweb/src/components/common/BottomSheetContents/areaSheet/AreaSheetHeader.tsx
  packages/climbingweb/src/components/common/DropDown/index.tsx
  packages/climbingweb/src/components/common/button/Button.tsx
  packages/climbingweb/src/components/common/divder/Divder.tsx
  packages/climbingweb/src/components/common/profileImage/ProfileImage.tsx
Labels: enhancement

#100 feat: implement center page
  .gitignore
  package.json
  packages/climbingweb/pages/SearchPage.tsx
  packages/climbingweb/pages/center/[cid].tsx
  packages/climbingweb/pages/center/index.tsx
  packages/climbingweb/pages/index.tsx
  packages/climbingweb/src/assets/icon/center_channel/ic_24_instagram.svg
  packages/climbingweb/src/assets/icon/center_channel/ic_24_tel_gray800.svg
  packages/climbingweb/src/assets/icon/center_channel/ic_24_web_gray800.svg
  packages/climbingweb/src/assets/icon/center_channel/ic_24_youtube.svg
  packages/climbingweb/src/assets/icon/ic_18_pin_gray600.svg
  packages/climbingweb/src/assets/icon/star_rating/ic_normal_star_gray.svg
  packages/climbingweb/src/assets/icon/star_rating/ic_normal_star_half.svg
  packages/climbingweb/src/assets/icon/star_rating/ic_normal_star_yellow.svg
  packages/climbingweb/src/assets/icon/star_rating/ic_small_star_gray.svg
  packages/climbingweb/src/assets/icon/star_rating/ic_small_star_yellow.svg
  packages/climbingweb/src/components/CenterInfo/CenterDetailInfo/CenterDetailInfo.tsx
  packages/climbingweb/src/components/CenterInfo/CenterDetailInfo/CenterPost.tsx
  packages/climbingweb/src/components/CenterInfo/CenterDetailInfo/CenterReview.tsx
  packages/climbingweb/src/components/CenterInfo/CenterInfoContent.tsx
  packages/climbingweb/src/components/CenterInfo/CenterInfoHead.tsx
  packages/climbingweb/src/components/Comments/ReviewComment.tsx
  packages/climbingweb/src/components/common/CenterResult/CenterResult.tsx
  packages/climbingweb/src/components/common/CenterResult/CenterResultList.tsx
  packages/climbingweb/src/components/common/CenterResult/type.d.ts
  packages/climbingweb/src/components/common/ImageList/ImageGridList.tsx
  packages/climbingweb/src/components/common/ImageList/index.tsx
  packages/climbingweb/src/components/common/StarRating/index.tsx
  packages/climbingweb/src/components/common/TabBar/index.tsx
  packages/climbingweb/src/components/common/TabBar/type.d.ts
  packages/climbingweb/src/components/common/button/Button.tsx
  packages/climbingweb/tailwind.config.js
  yarn-error.log
  yarn.lock
Labels: enhancement, chore

#114 Report
  packages/climbingweb/pages/CreatePostPage.tsx
  packages/climbingweb/pages/center/request/index.tsx
  packages/climbingweb/pages/center/review/index.tsx
  packages/climbingweb/pages/report/index.tsx
  packages/climbingweb/src/components/CreateFeed/ContentInput.tsx
  packages/climbingweb/src/components/SettingInfo/EditMyInfo.tsx
  packages/climbingweb/src/components/common/BottomSheetContents/ListSheet/ListSheet.tsx
  packages/climbingweb/src/components/common/BottomSheetContents/ListSheet/SheetHeader.tsx
  packages/climbingweb/src/components/common/TextArea/TextArea.tsx
Labels: enhancement, refactor

#112 My
  .gitignore
  package.json
  packages/climbingweb/next.config.js
  packages/climbingweb/pages/my/index.tsx
  packages/climbingweb/src/components/My/MyContent.tsx
  packages/climbingweb/src/components/My/MyHead.tsx
  packages/climbingweb/src/components/My/Private.tsx
  packages/climbingweb/src/components/common/bottomNav/button.tsx
  packages/climbingweb/src/components/common/divder/Divder.tsx
  packages/climbingweb/src/components/common/profileImage/ProfileImage.tsx
  yarn.lock
Labels: enhancement, chore

#111 feat: create page for one Feed
  packages/climbingweb/pages/feed/[fid].tsx
Labels: enhancement

#110 feat: implement Notification component
  packages/climbingweb/pages/SettingPage.tsx
  packages/climbingweb/src/components/SettingInfo/Notification/Notification.tsx
  packages/climbingweb/src/components/SettingInfo/Notification/NotificationList.tsx
  packages/climbingweb/src/components/SettingInfo/Notification/type.d.ts
Labels: enhancement

#109 feat: Routing pages
  packages/climbingweb/pages/CommentPage.tsx
  packages/climbingweb/pages/center/index.tsx
  packages/climbingweb/pages/feed/[fid]/comments/index.tsx
  packages/climbingweb/pages/feed/create/index.tsx
  packages/climbingweb/pages/index.tsx
  packages/climbingweb/pages/search/index.tsx
  packages/climbingweb/pages/setting/index.tsx
  packages/climbingweb/src/components/HomeFeed/FeedContent/FeedContent.tsx
  packages/climbingweb/src/components/common/CenterResult/CenterResult.tsx
  packages/climbingweb/src/components/common/CenterResult/CenterResultList.tsx
  packages/climbingweb/src/components/common/CenterResult/type.d.ts
Labels: enhancement

#117 feat: 페이지 별 바텀시트 적용
  packages/climbingweb/pages/_app.tsx
  packages/climbingweb/pages/center/[cid].tsx
  packages/climbingweb/pages/center/request/index.tsx
  packages/climbingweb/pages/index.tsx
  packages/climbingweb/pages/report/index.tsx
  packages/climbingweb/pages/search/index.tsx
  packages/climbingweb/pages/setting/index.tsx
  packages/climbingweb/src/components/HomeFeed/FeedHeader/FeedHeader.tsx
  packages/climbingweb/src/components/HomeFeed/HomeFeed.tsx
  packages/climbingweb/src/components/SettingInfo/EditMyInfo.tsx
  packages/climbingweb/src/components/common/BottomSheetContents/FeedEditSheet.tsx
  packages/climbingweb/src/components/common/BottomSheetContents/LeaveSheet.tsx
  packages/climbingweb/src/components/common/BottomSheetContents/ListSheet/ListSheet.tsx
  packages/climbingweb/src/components/common/BottomSheetContents/type.d.ts
  packages/climbingweb/src/components/common/DropDown/index.tsx
  packages/climbingweb/src/components/common/IconButton.tsx
  packages/climbingweb/src/components/common/bottomNav/NavBar.tsx
  packages/climbingweb/src/components/common/button/Button.tsx
  packages/climbingweb/src/hooks/useBtSheet.tsx
  packages/climbingweb/src/store/index.ts
  packages/climbingweb/src/store/slices/index.ts
  packages/climbingweb/src/store/slices/uiSlice.ts
  packages/climbingweb/tailwind.config.js
Labels: enhancement

#119 feat: 차단리스트 화면 구현
  packages/climbingweb/pages/setting/index.tsx
  packages/climbingweb/src/components/SettingInfo/BanList.tsx
  packages/climbingweb/src/components/common/LaonList/LaonCaencelButton.tsx
Labels: enhancement

#120 refactor: :recycle: next/Image와 SVG 아이콘 코드 분리
  packages/climbingweb/next.config.js
  packages/climbingweb/pages/ExampleList.stories.tsx
  packages/climbingweb/pages/ExampleList.tsx
  packages/climbingweb/src/assets/icon/ic_12_rate_black.svg
  packages/climbingweb/src/components/CenterInfo/CenterInfoHead.tsx
  packages/climbingweb/src/components/CreateFeed/UploadImageList/UploadImage.tsx
  packages/climbingweb/src/components/CreateFeed/UploadImageList/UploadImageButton.tsx
  packages/climbingweb/src/components/HomeFeed/FeedContent/FeedContent.tsx
  packages/climbingweb/src/components/HomeFeed/FeedHeader/FeedHeader.tsx
  packages/climbingweb/src/components/HomeFeed/FeedSectorInfo/FeedSectorInfo.tsx
  packages/climbingweb/src/components/ImageSlider/ImageSlider.tsx
  packages/climbingweb/src/components/SearchResult/RaonResult/RaonResult.tsx
  packages/climbingweb/src/components/SearchResult/SearchBar/SearchBar.tsx
  packages/climbingweb/src/components/SettingInfo/EditMyInfo.tsx
  packages/climbingweb/src/components/SettingInfo/VersionInfo.tsx
  packages/climbingweb/src/components/common/CenterResult/CenterResult.tsx
  packages/climbingweb/src/components/common/DropDown/index.tsx
  packages/climbingweb/src/components/common/IconButton.tsx
  packages/climbingweb/src/components/common/ImageList/ImageGridList.tsx
  packages/climbingweb/src/components/common/ImageList/index.tsx
  packages/climbingweb/src/components/common/bottomNav/button.tsx
  packages/climbingweb/src/components/common/profileImage/ProfileImage.tsx
Labels: enhancement

#123 fix: :bug: 자동 다크모드 버그 이슈 핫픽스
  packages/climbingweb/pages/_document.tsx
Labels: bug

#121 feat: 누락된 스토리북 컴포넌트 추가
  .storybook/preview-head.html
  packages/climbingweb/pages/center/[cid].tsx
  packages/climbingweb/pages/center/index.tsx
  packages/climbingweb/pages/center/request/index.tsx
  packages/climbingweb/pages/center/review/index.tsx
  packages/climbingweb/pages/feed/[fid].tsx
  packages/climbingweb/pages/feed/create/index.tsx
  packages/climbingweb/pages/index.tsx
  packages/climbingweb/pages/my/index.tsx
  packages/climbingweb/pages/report/index.tsx
  packages/climbingweb/pages/setting/index.tsx
  packages/climbingweb/src/components/common/AppBar/IconButton.tsx
  packages/climbingweb/src/components/common/AppBar/NextButton.tsx
  packages/climbingweb/src/components/common/AppBar/index.stories.tsx
  packages/climbingweb/src/components/common/AppBar/index.tsx
  packages/climbingweb/src/components/common/BottomSheetContents/ButtonSheet/index.stories.tsx
  packages/climbingweb/src/components/common/BottomSheetContents/ButtonSheet/index.tsx
  packages/climbingweb/src/components/common/BottomSheetContents/FeedEditSheet.tsx
  packages/climbingweb/src/components/common/BottomSheetContents/ListSheet/Sheet.stories.tsx
  packages/climbingweb/src/components/common/CenterResult/CenterResult.stories.tsx
  packages/climbingweb/src/components/common/ImageList/ImageGridList.stories.tsx
  packages/climbingweb/src/components/common/ImageList/index.stories.tsx
  packages/climbingweb/src/components/common/LaonList/LaonList.stories.tsx
  packages/climbingweb/src/components/common/StarRating/index.stories.tsx
  packages/climbingweb/src/components/common/TabBar/index.stories.tsx
  packages/climbingweb/src/components/common/TextArea/TextArea.stories.tsx
  packages/climbingweb/src/components/common/bottomNav/NavBar.stories.tsx
  packages/climbingweb/src/components/common/bottomNav/NavButton.tsx
  packages/climbingweb/src/components/common/button/NormalButton.stories.tsx
  packages/climbingweb/src/components/common/button/SmallNodeButton.stories.tsx
  packages/climbingweb/src/components/common/divder/Divider.stories.tsx
  packages/climbingweb/src/components/common/profileImage/ProfileImage.stories.tsx
  packages/climbingweb/src/components/common/profileImage/ProfileImage.tsx
Labels: enhancement, refactor

#125 feat: 피드 작성 페이지 마크업 구현
  packages/climbingweb/next.config.js
  packages/climbingweb/pages/feed/create/index.tsx
  packages/climbingweb/src/assets/icon/createFeed/ic_24_minus_gray800.svg
  packages/climbingweb/src/components/CreateFeed/SelectHoldList/HoldImage.tsx
  packages/climbingweb/src/components/CreateFeed/SelectHoldList/HoldImageButton.tsx
  packages/climbingweb/src/components/CreateFeed/SelectHoldList/HoldListModal.tsx
  packages/climbingweb/src/components/CreateFeed/type.d.ts
  packages/climbingweb/src/components/common/PageSubTitle/PageSubTitle.tsx
  packages/climbingweb/src/interface/Hold.tsx
Labels: enhancement, refactor
