Repository Co-Laon/claon-app, pull requests merged in 2023-02, with the labels that each got.

#203 chore: firebase 배포 cd 구축, 기존 ci 빌드 테스트 추가
  .github/workflows/ci.yml
  .github/workflows/firebase-hosting-merge.yml
  .github/workflows/firebase-hosting-pull-request.yml
  packages/climbingweb/firebase.json
Labels: chore

#206 chore: proguard - 코드 난독화 기능 - 미사용으로 변경 -> 크래시 미발생
  packages/climbingapp/android/app/build.gradle
Labels: fix

#205 [WIP] fix: #192 사용자 정보 입력화면, 인스타그램 연동화면 버그 fix
  packages/climbingapp/src/component/appBar/AppBar.tsx
  packages/climbingapp/src/component/appBar/Skip.tsx
  packages/climbingapp/src/component/text-input/TextInput.tsx
  packages/climbingapp/src/navigation/screens/auth/ConnectWithInstagramScreen.tsx
  packages/climbingapp/src/navigation/screens/auth/SignUpStepOneScreen.tsx
  packages/climbingapp/src/navigation/screens/auth/SignUpStepTwoScreen.tsx
  packages/climbingapp/src/navigation/screens/auth/WelcomeScreen.tsx
Labels: fix

#207 fix: 앱 재실행 시 토큰 저장 확인 후 자동 로그인 적용, 로그아웃 시 토큰만료 후 로그인 화면 이동하도록 로직 수정
  packages/climbingapp/src/component/webview/CustomWebView.tsx
  packages/climbingapp/src/hooks/useAuth.ts
  packages/climbingapp/src/navigation/LoginNavigator.tsx
  packages/climbingapp/src/store/slices/auth.ts
  packages/climbingapp/src/utils/storage.ts
Labels: fix

#204 fix: oauth 로그인 실패 시 회원가입 화면으로 바로 넘어가는 로직 수정
  packages/climbingapp/src/hooks/useAuth.ts
  packages/climbingapp/src/navigation/screens/auth/LoginScreen.tsx
  packages/climbingapp/src/types/type.d.ts
Labels: fix

#208 [WIP] fix: #191, #190 버그 수정 ( 닉네임 체크, 프로필 사진 S3 업로드)
  packages/climbingapp/src/component/profile-image/ProfileImage.tsx
  packages/climbingapp/src/hooks/queries/sign/queries.ts
  packages/climbingapp/src/hooks/useAuth.ts
  packages/climbingapp/src/navigation/screens/auth/ConnectWithInstagramScreen.tsx
  packages/climbingapp/src/navigation/screens/auth/SignUpStepOneScreen.tsx
  packages/climbingapp/src/store/slices/auth.ts
  packages/climbingapp/src/store/slices/index.ts
  packages/climbingapp/src/store/slices/s3util.ts
  packages/climbingapp/src/utils/constants.ts
  packages/climbingapp/src/utils/errorMessage.ts
Labels: fix

#209 fix: android 가로모드 고정, pinch zoom 막기, user-select (텍스트 복사 등) 막기 적용
  packages/climbingapp/android/app/src/main/AndroidManifest.xml
  packages/climbingapp/src/component/webview/CustomWebView.tsx
  packages/climbingapp/src/utils/constants.ts
Labels: fix, chore, style

#211 fix: redux 비동기 상태 체크 적용 => auto 로그인 분기처리 로직수정
  packages/climbingapp/src/hooks/useGetTokenFromStorage.ts
  packages/climbingapp/src/navigation/LoginNavigator.tsx
  packages/climbingapp/src/store/slices/auth.ts
Labels: fix

#221 refac&fix: #212, #214 버그 fix 와 useMutation custom hooks 리팩터링
  packages/climbingweb/pages/feed/create/index.tsx
  packages/climbingweb/pages/report/[fid].tsx
  packages/climbingweb/pages/users/name/[uname]/index.tsx
  packages/climbingweb/src/components/SearchResult/UserResult/UserResult.tsx
  packages/climbingweb/src/hooks/queries/center/queryKey.ts
  packages/climbingweb/src/hooks/queries/laon/queryKey.ts
  packages/climbingweb/src/hooks/queries/post/queryKey.ts
  packages/climbingweb/src/hooks/queries/user/queryKey.ts
Labels: refactor, fix

#218 fix: 회원가입/로그인 키보드 노출 시 스크린 동작 방식 수정
  packages/climbingapp/App.tsx
  packages/climbingapp/package.json
  packages/climbingapp/src/component/appBar/ Back.tsx
  packages/climbingapp/src/component/appBar/Skip.tsx
  packages/climbingapp/src/hooks/useKeyboard.ts
  packages/climbingapp/src/navigation/LoginNavigator.tsx
  packages/climbingapp/src/navigation/screens/auth/ConnectWithInstagramScreen.tsx
  packages/climbingapp/src/navigation/screens/auth/LoginScreen.tsx
  packages/climbingapp/src/navigation/screens/auth/OptionalInfoScreen.tsx
  packages/climbingapp/src/navigation/screens/auth/RegisterScreen.tsx
  packages/climbingapp/src/navigation/screens/auth/SignUpStepOneScreen.tsx
  packages/climbingapp/src/navigation/screens/auth/SignUpStepTwoScreen.tsx
  packages/climbingapp/src/theme/index.ts
  packages/climbingapp/src/theme/styled.d.ts
  yarn.lock
Labels: fix

#219 fix: 로그아웃, 회원탈퇴 로직 추가 및 수정
  packages/climbingapp/src/component/webview/CustomWebView.tsx
  packages/climbingapp/src/hooks/useAuth.ts
Labels: fix

#223 fix: nextjs 에서 useLayoutEffect warning 제거
  packages/climbingweb/pages/_app.tsx
  packages/climbingweb/src/hooks/useIsomorphicLayoutEffect.ts
Labels: fix

#225 fix: 센터의 웹, 인스타, 유투브 등 링킹 방식 수정
  packages/climbingapp/src/component/webview/CustomWebView.tsx
  packages/climbingweb/src/components/CenterInfo/CenterInfoHead.tsx
Labels: fix

#239 chore: firebase 캐시설정 추가
  packages/climbingweb/firebase.json
Labels: chore

#240 style: 마이페이지 스타일 변경
  packages/climbingweb/src/components/User/MiniHold.tsx
  packages/climbingweb/src/components/User/UserContent.tsx
  packages/climbingweb/src/components/User/UserFeed.tsx
  packages/climbingweb/src/components/User/UserFeedList.tsx
  packages/climbingweb/src/components/User/UserHead.tsx
  packages/climbingweb/src/components/User/UserPageLayout.tsx
  packages/climbingweb/src/components/User/UserRecord.tsx
Labels: style

#262 fix:크로매틱 ci node 버전에 의한 에러 수정
  .github/workflows/chromatic.yml
Labels: bug
